# Sakai Gitpod configuration file
tasks:
  - name: "Sakai Dev Environment"
  - command: "sh ./gitpod-scripts.sh"




# vscode extensions
vscode:
    extensions:
      - cweijan.vscode-mysql-client2

# Open port
ports:
  - port: 8080
    onOpen: open-preview
