# Sakai Gitpod configuration file
tasks:
  - name: "Sakai Dev Environment"
  - before: "sh ./gitpod-scripts/build-sakai.sh && gp sync done"

  - name: "Start Tomcat Server"
  - init: "gp sync await"
  - command: "sh ./gitpod-scripts/start-tomcat.sh"




# vscode extensions
vscode:
    extensions:
      - cweijan.vscode-mysql-client2


ports:
  - port: 8080
    onOpen: open-preview
